version: 2

linters:
  disable-all: true
  enable:
    # --- The Critical Checks (Gap Fixers) ---
    - errcheck # Catches your file.Close errors
    - gosec # Catches your G304 security issue
    - revive # Catches your missing comment issues
    - govet # Standard Go vetting

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

  goimports:
    local-prefixes: github.com/mikemadden42

issues:
  exclude-dirs:
    - third_party
    - builtin
    - examples
